version: "3.5"

services:
  automation_jenkns:
    user: root
    container_name: "automation_jenkins"
    image: jenkins/jenkins
    restart: always
    ports:
      - "9000:8080"
    volumes:
      - ~/testing-jenkins/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
